BBBatScale/core/urls.py
from django.urls import path

from core import views

urlpatterns = [
    path('api/callback/bbb/', views.callback_bbb, name="callback_bbb"),
    path('api/recording/postporocessing/done/', views.recording_callback),
    path('api/servers/registration/', views.api_server_registration, name="api_server_registration"),
    path('servers/overview', views.servers_overview, name="servers_overview"),
    path('rooms/overview', views.rooms_overview, name="rooms_overview"),
    path('tenants/overview', views.tenant_overview, name="tenants_overview"),
    path('rooms/configs/overview', views.room_config_overview, name="room_configs_overview"),

    path('server/create/', views.server_create, name="server_create"),
    path('server/delete/<int:server>', views.server_delete, name="server_delete"),
    path('server/update/<int:server>', views.server_update, name="server_update"),

    path('room/create/', views.room_create, name="room_create"),
    path('room/delete/<int:room>', views.room_delete, name="room_delete"),
    path('room/update/<int:room>', views.room_update, name="room_update"),

    path('home_room/update<int:home_room>', views.home_room_update, name="home_room_update"),

    path('personal_room/create', views.personal_room_create, name="personal_room_create"),
    path('personal_room/update/<int:personal_room>', views.personal_room_update,
         name="personal_room_update"),
    path('personal_room/delete/<int:personal_room>', views.personal_room_delete,
         name="personal_room_delete"),

    path('statistics', views.statistics, name="statistics"),

    path('importexport', views.import_export, name="import_export"),
    path('export/json', views.export_download_json, name="export_download_json"),
    path('export/csv', views.export_download_csv, name="export_download_csv"),
    path('import/json', views.import_upload_json, name="import_upload_json"),
    path('import/csv', views.import_upload_csv, name="import_upload_csv"),

    path('room/config/create/', views.room_config_create, name="room_config_create"),
    path('room/config/delete/<int:room_config>', views.room_config_delete, name="room_config_delete"),
    path('room/config/update/<int:room_config>', views.room_config_update, name="room_config_update"),

    path('tenant/create/', views.tenant_create, name="tenant_create"),
    path('tenant/delete/<int:tenant>', views.tenant_delete, name="tenant_delete"),
    path('tenant/update/<int:tenant>', views.tenant_update, name="tenant_update"),

    path('recordings/overview/', views.recordings_list, name="recordings_list"),

    path('users/overview/', views.users_overview, name="users_overview"),
    path('user/create/', views.user_create, name="user_create"),
    path('user/change/password/', views.change_password, name="change_password"),
    path('user/change/theme/', views.change_theme, name="change_theme"),
    path('user/delete/<int:user>', views.user_delete, name="user_delete"),
    path('user/update/<int:user>', views.user_update, name="user_update"),

    path('groups/overview/', views.groups_overview, name="groups_overview"),
    path('group/create/', views.group_create, name="group_create"),
    path('group/delete/<int:group>', views.group_delete, name="group_delete"),
    path('group/update/<int:group>', views.group_update, name="group_update"),

    path('join/create/meeting/<str:meeting_id>', views.join_or_create_meeting, name="join_or_create_meeting"),
    path('create/meeting/<str:meeting_id>', views.create_meeting, name="create_meeting"),
    path('set/username/join/<str:meeting_id>', views.session_set_username_pre_join, name="set_username_pre_join"),
    path('join/meeting/<str:meeting_id>', views.join_meeting, name="join_meeting"),
    path('join/meeting/anon/', views.session_set_username, name="session_set_username"),
    path('meeting/status/<str:meeting_id>', views.get_meeting_status, name="get_meeting_status"),
    path('room/meeting/end/<int:room_pk>', views.force_end_meeting, name="force_end_meeting"),

    path('<str:tenant_name>/bigbluebutton/api/', views.bbb_initialization_request),
    path('<str:tenant_name>/bigbluebutton/api/join', views.bbb_api_join),
    path('<str:tenant_name>/bigbluebutton/api/create', views.bbb_api_create),
    path('<str:tenant_name>/bigbluebutton/api/getMeetingInfo', views.bbb_api_get_meeting_info),
    path('<str:tenant_name>/bigbluebutton/api/end', views.bbb_api_end),
    path('<str:tenant_name>/bigbluebutton/api/getRecordings', views.bbb_api_get_recordings),

    path('settings', views.settings_edit, name="settings_edit"),
    path('coowner/user/search', views.json_search_user, name="json_search_user")
]

BBBatScale/core/models.py
from __future__ import annotations

import random
import logging
from collections import defaultdict
from datetime import timedelta
from math import ceil
from typing import Optional

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db import transaction
from django.db.models import Sum
from django.db.models.signals import m2m_changed
from django.templatetags.static import static
from django.utils.crypto import get_random_string
from django.utils.timezone import now
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from core.constants import SERVER_STATES, SERVER_STATE_WAITING_RESPONSE, SERVER_STATE_ERROR, \
    SCHEDULING_STRATEGY_LEAST_PARTICIPANTS, SERVER_STATE_UP, SERVER_STATE_DISABLED, \
    SCHEDULING_STRATEGY_LEAST_UTILIZATION, GUEST_POLICY, GUEST_POLICY_ALLOW, ROOM_STATE, ROOM_STATE_INACTIVE, \
    SCHEDULING_STRATEGY_RANDOM_PICK_FROM_LEAST_UTILIZED, \
    SCHEDULING_STRATEGIES, ROOM_STATE_ACTIVE, WEBHOOKS
from core.utils import BigBlueButton

logger = logging.getLogger(__name__)


def get_default_room_config():
    return RoomConfiguration.objects.get_or_create(name="Default")[0]


class User(AbstractUser):
    theme = models.ForeignKey("Theme", on_delete=models.SET_NULL, null=True)
    personal_rooms_max_number = models.IntegerField(null=True, blank=True)
    display_name = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self) -> str:
        if self.display_name:
            return self.display_name
        elif self.first_name and self.last_name:
            return f"{self.last_name}, {self.first_name}"
        elif self.first_name:
            return self.first_name
        elif self.last_name:
            return self.last_name
        elif self.email:
            return self.email
        return gettext("Unknown")

    def get_max_number_of_personal_rooms(self):
        if self.personal_rooms_max_number is not None:
            return self.personal_rooms_max_number
        else:
            general_parameters: GeneralParameter = GeneralParameter.load()
            if self.groups.filter(name=settings.MODERATORS_GROUP).exists():
                return general_parameters.personal_rooms_teacher_max_number
            else:
                return general_parameters.personal_rooms_non_teacher_max_number

    def get_theme(self) -> Theme:
        theme = self.theme
        if theme is None:
            theme = GeneralParameter.load().default_theme
        return theme


class Tenant(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    notifications_emails = models.TextField(null=True, blank=True)
    token_registration = models.CharField(max_length=255, null=True, blank=True)
    scheduling_strategy = models.CharField(max_length=255, choices=SCHEDULING_STRATEGIES,
                                           default=SCHEDULING_STRATEGY_LEAST_UTILIZATION)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.token_registration:
            self.token_registration = get_random_string(length=10)
        super(Tenant, self).save(*args, **kwargs)

    def get_current_participant_count(self):
        return self.room_set.all().aggregate(Sum('participant_count'))['participant_count__sum']

    def get_utilization(self):
        usage = 0
        for server in self.get_servers_up():
            usage = usage + server.get_utilization()
        return ceil(usage)

    def get_utilization_max(self):
        return ceil(sum(map(lambda server: server.videostream_count_max, self.get_servers_up())))

    def get_utilization_percent(self):
        utilization_max = self.get_utilization_max()
        return 0 if utilization_max <= 0 else int(round(self.get_utilization() / utilization_max, 2) * 100)

    def get_server_for_room(self):  # noqa C901 # TODO needs to be refactored due to very high complexity
        server_to_be = None
        worker = ServerType.objects.get(name="worker")
        logger.info("Selecting new server for scheduling with strategy: {}".format(self.scheduling_strategy))

        if self.scheduling_strategy == SCHEDULING_STRATEGY_LEAST_PARTICIPANTS:
            min_count = 1000
            for server in self.server_set.filter(state=SERVER_STATE_UP, server_types__in=[worker]):
                pc = server.get_participant_count()
                if pc < min_count:
                    min_count = pc
                    server_to_be = server
                    logger.info("Best candidate so far: {}".format(server_to_be))

        if self.scheduling_strategy == SCHEDULING_STRATEGY_LEAST_UTILIZATION:
            min_count = 1000
            for server in self.server_set.filter(state=SERVER_STATE_UP, server_types__in=[worker]):
                pc = server.get_utilization()
                if pc < min_count:
                    min_count = pc
                    server_to_be = server
                    logger.info("Best candidate so far: {}".format(server_to_be))

        if self.scheduling_strategy == SCHEDULING_STRATEGY_RANDOM_PICK_FROM_LEAST_UTILIZED:

            def get_server_utilization_list():
                servers_utilization = []
                for server in self.server_set.filter(state=SERVER_STATE_UP, server_types__in=[worker]):
                    servers_utilization.append([server.get_utilization(), server])

                servers_utilization_sorted = sorted(servers_utilization, key=lambda x: x[0])

                return servers_utilization_sorted

            def get_servers_with_zero_utilization(server_utilization_list):
                zero_utilization_servers = []
                for utilization, server in server_utilization_list:
                    if utilization == 0:
                        zero_utilization_servers.append(server)

                return zero_utilization_servers

            def get_server_with_least_utilization(server_utilization_list, min_number_of_least_utilized_servers):
                utilizations_with_servers = defaultdict(list)
                for utilization, server in server_utilization_list:
                    utilizations_with_servers[utilization].append(server)

                sorted_utilizations_server_share = sorted(utilizations_with_servers.keys())

                selected_servers = []

                for utilization in sorted_utilizations_server_share:
                    selected_servers += utilizations_with_servers[utilization]

                    if len(selected_servers) >= min_number_of_least_utilized_servers:
                        break

                return selected_servers

            def randomy_pick_server_from_list(candidates):
                return random.choice(candidates)

            min_server_candidates = 5
            min_servers_candidates_with_zero_utilization = 5
            server_utilization_list = get_server_utilization_list()

            servers_with_zero_utilization = get_servers_with_zero_utilization(server_utilization_list)
            if len(servers_with_zero_utilization) >= min_servers_candidates_with_zero_utilization:
                server_to_be = randomy_pick_server_from_list(servers_with_zero_utilization)
            else:
                least_utilized_servers = get_server_with_least_utilization(server_utilization_list,
                                                                           min_server_candidates)
                server_to_be = randomy_pick_server_from_list(least_utilized_servers)

            logger.info("Best candidate so far = {} from server utilization list: {}".format(server_to_be,
                                                                                             server_utilization_list))

        logger.info("Selected : {}".format(server_to_be))

        return server_to_be

    def get_servers_up(self):
        return self.server_set.filter(state=SERVER_STATE_UP)


class RoomConfiguration(models.Model):
    name = models.CharField(max_length=255, unique=True)
    mute_on_start = models.BooleanField(default=True)
    all_moderator = models.BooleanField(default=False)
    everyone_can_start = models.BooleanField(default=False)
    authenticated_user_can_start = models.BooleanField(default=False)
    guest_policy = models.CharField(max_length=30, choices=GUEST_POLICY, default=GUEST_POLICY_ALLOW, blank=True)
    allow_guest_entry = models.BooleanField(default=False)
    access_code = models.CharField(max_length=255, null=True, blank=True)
    access_code_guests = models.CharField(max_length=255, null=True, blank=True)
    disable_cam = models.BooleanField(default=False)
    disable_mic = models.BooleanField(default=False)
    allow_recording = models.BooleanField(default=False)
    disable_private_chat = models.BooleanField(default=False)
    disable_public_chat = models.BooleanField(default=False)
    disable_note = models.BooleanField(default=False)
    url = models.CharField(max_length=255, null=True, blank=True)
    dialNumber = models.CharField(max_length=255, null=True, blank=True)
    logoutUrl = models.CharField(max_length=255, null=True, blank=True)
    welcome_message = models.CharField(max_length=255, null=True, blank=True)
    maxParticipants = models.PositiveIntegerField(blank=True, null=True)
    streamingUrl = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class ServerType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Server(models.Model):
    tenant = models.ForeignKey(Tenant, on_delete=models.SET_NULL, null=True)
    server_types = models.ManyToManyField(ServerType)
    dns = models.CharField(max_length=255, unique=True)

BBBatScale/core/templates/change_theme.html
{% extends "base.html" %}
{% load i18n %}
{% load theme %}

{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card card-info">
                <div class="card-header">
                    <span class="card-title">{% translate "Change Theme" %}</span>
                </div>
                <div class="card-body">
                    <form id="change-theme" method="POST" action="{% url "change_theme" %}">
                        {% csrf_token %}
                        {% for theme in themes %}
                            <div class="form-group">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="radio" name="theme" value="{{ theme.pk }}"
                                               {% if request.user.get_theme == theme %}checked{% endif %}>
                                        {{ theme.name }}
                                    </label>
                                </div>
                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-8">
                        </div>
                        <div class="col-4">
                            <button class="btn btn-primary btn-block" form="change-theme" type="submit">
                                {% translate "Change" %}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

BBBatScale/core/templates/configure_room_for_meeting.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Start a room" %}</h3>
                        </div>

                        <div class="card-body">
                            <p>
                                Room <strong>{{ room }}</strong> is configured as <strong>{{ room.config }}</strong>
                                with the following parameters. If you need a different configuration feel free to modify
                                the parameters and press start.
                            </p>
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

BBBatScale/core/templates/group_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load theme %}

{% block styles %}
    {% theme "multi_select" "stylesheet" %}
{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Group form" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}

                        </div>

                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

BBBatScale/core/templates/import_export.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    {% if uniq_constraints %}
        <div class="row mt-2">
            <div class="col-md-6">
                <strong>multiple unique names detected: </strong> <br>

                {% for dup in uniq_constraints %}
                    => {{ dup }} <br>
                {% endfor %}
                <br>
                <br>
            </div>
        </div>
    {% else %}
        <div class="row mt-2">
            <div class="col-md-6">
                Import / Export
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <div class="row">
                        <div class="col-2">
                            <a class="btn btn-primary" href="{% url 'export_download_json' %}"> Download Export
                                JSON </a>
                        </div>
                        <div class="col-10">
                            <form method="post" enctype="multipart/form-data"
                                  action="{% url 'import_upload_json' %}">
                                {% csrf_token %}
                                <input type="file" name="document">
                                <button class="btn btn-primary" type="submit"> Upload Import JSON</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="card-box">
                    <div class="row">
                        <div class="col-2">
                            <a class="btn btn-primary" href="{% url 'export_download_csv' %}"> Download Export
                                CSV </a>
                        </div>
                        <div class="col-10">
                            <form method="post" enctype="multipart/form-data"
                                  action="{% url 'import_upload_csv' %}">
                                {% csrf_token %}
                                <input type="file" name="document">
                                <button class="btn btn-primary" type="submit"> Upload Import CSV</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

BBBatScale/core/templates/password_change.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Password change form" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

BBBatScale/core/templates/room_configs_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Configure room type" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

BBBatScale/core/templates/servers_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}
{% load theme %}

{% block styles %}
    {% theme "multi_select" "stylesheet" %}
{% endblock styles %}

{% block scripts %}
    <script src="{% static 'plugins/multi-select/js/jquery.multi-select.js' %}"></script>
    <script>
        jQuery(function () {
            window.select = jQuery('#id_server_types').multiSelect();
        });
    </script>
{% endblock scripts %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Configure server" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

BBBatScale/core/templates/tenants_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{% trans "Tenant form" %}</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

BBBatScale/core/templates/tenants_overview.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block scripts %}
    <script>
        function deleteTenant(url) {
            jQuery('#delete_tenant').attr('href', url);
            jQuery('#delete_tenant_modal').modal('toggle');
        }
    </script>
{% endblock %}

{% block content %}
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-1">
                <div class="col-12 card">
                    <div class="card-body">
                        {% crispy filter.form filter.form.helper %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title" id="table_desc">{% trans "Tenants overview" %}<span
                                    class="badge badge-pill badge-primary ml-1">{{ filter.qs.count }}</span></h3>
                            <div class="card-tools">
                                <a class="btn btn-sm btn-default float-right" href="{% url 'tenant_create' %}"><em
                                        class="fas fa-plus"></em></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table aria-describedby="table_desc" class="table table-hover table-sm">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">{% trans "Name" %}</th>
                                    <th scope="col">{% trans "Scheduling Strategy" %}</th>
                                    <th scope="col">{% trans "Description" %}</th>
                                    <th scope="col">{% trans "Email Notifications" %}</th>
                                    <th scope="col" class="text-right">{% trans "Action" %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for tenant in filter.qs %}
                                    <tr>
                                        <td>{{ tenant.name }}</td>
                                        <td>{{ tenant.get_scheduling_strategy_display }}</td>
                                        <td>{{ tenant.description|default_if_none:"" }}</td>
                                        <td>{{ tenant.notifications_emails }}</td>
                                        <td>
                                            <div class="btn-group btn-group-sm float-right">
                                                <a class="btn btn-success"
                                                   href="{% url 'tenant_update' tenant.pk %}"
                                                   data-toggle="tooltip" data-placement="top"
                                                   title="{% trans "Edit" %}">
                                                    <em class="fas fa-pen"></em>
                                                </a>
                                                <button class="btn btn-danger"
                                                        onclick="deleteTenant('{% url "tenant_delete" tenant.pk %}')"
                                                        data-toggle="tooltip" data-placement="top"
                                                        title="{% trans "Delete" %}">
                                                    <em class="fas fa-trash-alt"></em>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div id="delete_tenant_modal" class="modal fade" tabindex="-1" role="dialog"
         aria-labelledby="CenterModalLabel"
         aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="CenterModalLabel">{% trans "Delete tenant" %}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    {% trans "Are you sure you want to delete the tenant?" %}
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" href=""
                       data-toggle="tooltip" data-placement="top" title="Löschen" id="delete_tenant">
                        {% trans "Delete" %}
                    </a>
                    <button type="button" class="btn btn-secondary waves-effect"
                            data-dismiss="modal">{% trans "Cancel" %}</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
{% endblock %}